"""
customer_summary_service.py

Purpose
-------
Generates an explainable customer risk summary using the
customer profile and rule-based assessment results.

The summary produced by this service is intended for
credit analysts and underwriters and provides an
interpretable view of the customer's overall credit
position.

Responsibilities
----------------
- Generate executive customer summary
- Identify customer strengths
- Highlight risk factors
- Provide supporting evidence
- Produce explainable customer narrative

Out of Scope
------------
- Database access
- Business rule evaluation
- Customer assessment
- Recommendation generation

Author
------
Credit Risk Research Agent
"""

from typing import Any, Dict, List


class CustomerSummaryService:
    """
    Service responsible for generating an explainable
    customer risk summary.

    The service consumes customer profile information and
    assessment results generated by the
    CustomerAssessmentService.

    No business rules are evaluated within this service.
    """

    # ---------------------------------------------------------
    # Public Interface
    # ---------------------------------------------------------

   def generate_customer_summary(
        self,
        customer_profile: Dict[str, Any],
        assessment: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Generate a complete customer risk summary.
    
        Parameters
        ----------
        customer_profile : dict
            Complete customer profile retrieved from the repository.
    
        assessment : dict
            Assessment generated by CustomerAssessmentService.
    
        Returns
        -------
        dict
            Structured customer risk summary.
        """
    
        if not customer_profile:
    
            raise ValueError(
                "Customer profile cannot be empty."
            )
    
        if not assessment:
    
            raise ValueError(
                "Assessment cannot be empty."
            )
    
        return {
    
            "overall_risk":
                assessment["overall_summary"]["rating"],
    
            "executive_summary":
                self._build_executive_summary(
                    customer_profile,
                    assessment
                ),
    
            "strengths":
                self._identify_strengths(
                    assessment
                ),
    
            "risk_factors":
                self._identify_risk_factors(
                    assessment
                ),
    
            "key_observations":
                self._identify_key_observations(
                    customer_profile
                ),
    
            "supporting_evidence":
                self._collect_supporting_evidence(
                    assessment
                )
        }

    # ---------------------------------------------------------
    # Summary Builders
    # ---------------------------------------------------------

    def _build_executive_summary(
        self,
        customer_profile: Dict[str, Any],
        assessment: Dict[str, Any]
    ) -> str:
        """
        Build an executive summary describing the customer's
        overall credit profile.
        """
    
        customer = customer_profile.get("customer", {})
    
        name = (
            f"{customer.get('first_name', '')} "
            f"{customer.get('last_name', '')}"
        ).strip()
    
        overall_risk = assessment["overall_summary"]["rating"]
    
        return (
            f"{name} is assessed as '{overall_risk}'. "
            "The assessment is based on the customer's credit bureau "
            "profile, repayment behaviour, debt obligations and "
            "other supporting credit indicators."
        )

    def _identify_strengths(
        self,
        assessment: Dict[str, Any]
    ) -> List[str]:
        """
        Identify positive credit characteristics.
        """
    
        strengths = []
    
        if assessment["credit_score"]["rating"] in (
            "Excellent",
            "Good"
        ):
            strengths.append(
                assessment["credit_score"]["reason"]
            )
    
        if assessment["dti_ratio"]["rating"] == "Low":
            strengths.append(
                assessment["dti_ratio"]["reason"]
            )
    
        if assessment["payment_history"]["rating"] == "Excellent":
            strengths.append(
                assessment["payment_history"]["reason"]
            )
    
        if assessment["fraud_indicator"]["rating"] == "Clear":
            strengths.append(
                assessment["fraud_indicator"]["reason"]
            )
    
        return strengths

    def _identify_risk_factors(
        self,
        assessment: Dict[str, Any]
    ) -> List[str]:
        """
        Identify customer risk factors.
        """
    
        risks = []
    
        if assessment["credit_score"]["rating"] == "Poor":
            risks.append(
                assessment["credit_score"]["reason"]
            )
    
        if assessment["credit_utilization"]["rating"] == "High":
            risks.append(
                assessment["credit_utilization"]["reason"]
            )
    
        if assessment["dti_ratio"]["rating"] == "High":
            risks.append(
                assessment["dti_ratio"]["reason"]
            )
    
        if assessment["payment_history"]["rating"] == "Poor":
            risks.append(
                assessment["payment_history"]["reason"]
            )
    
        if assessment["fraud_indicator"]["rating"] == "High Risk":
            risks.append(
                assessment["fraud_indicator"]["reason"]
            )
    
        return risks

    def _identify_key_observations(
        self,
        customer_profile: Dict[str, Any]
    ) -> List[str]:
        """
        Identify noteworthy customer observations.
        """
    
        customer = customer_profile.get("customer", {})
    
        observations = [
    
            (
                f"Customer Segment: "
                f"{customer.get('customer_segment')}"
            ),
    
            (
                f"Employment Type: "
                f"{customer.get('employment_type')}"
            ),
    
            (
                f"Occupation: "
                f"{customer.get('occupation')}"
            ),
    
            (
                f"Annual Income: "
                f"{customer.get('annual_income'):,.2f}"
            ),
    
            (
                f"Relationship Duration: "
                f"{customer.get('relationship_years')} years"
            )
        ]
    
        return observations

    def _collect_supporting_evidence(
        self,
        assessment: Dict[str, Any]
    ) -> List[str]:
        """
        Collect evidence supporting the assessment.
        """
    
        evidence = []
    
        for item in assessment.values():
    
            if not isinstance(item, dict):
                continue
            if key == "overall_summary":
                continue
    
            evidence.append(
    
                f"{item['metric']}: {item['value']}"
            )


    # ---------------------------------------------------------
    #  Test Harness
    # ---------------------------------------------------------

if __name__ == "__main__":

    from repository.customer_repository import CustomerRepository
    from services.customer_assessment_service import CustomerAssessmentService

    repository = CustomerRepository()

    profile = repository.get_customer_profile("CUST000001")

    assessment_service = CustomerAssessmentService()

    assessment = assessment_service.assess_customer(profile)

    summary_service = CustomerSummaryService()

    summary = summary_service.generate_customer_summary(
        profile,
        assessment
    )

    from pprint import pprint

    pprint(summary)
    
        return evidence
