"""
customer_summary_service.py

Purpose
-------
Generates an explainable customer risk summary using the
customer profile and rule-based assessment results.

The summary produced by this service is intended for
credit analysts and underwriters and provides an
interpretable view of the customer's overall credit
position.

Responsibilities
----------------
- Generate executive customer summary
- Identify customer strengths
- Highlight risk factors
- Provide supporting evidence
- Produce explainable customer narrative

Out of Scope
------------
- Database access
- Business rule evaluation
- Customer assessment
- Recommendation generation

Author
------
Credit Risk Research Agent
"""

from typing import Any, Dict, List


class CustomerSummaryService:
    """
    Service responsible for generating an explainable
    customer risk summary.

    The service consumes customer profile information and
    assessment results generated by the
    CustomerAssessmentService.

    No business rules are evaluated within this service.
    """

    # ---------------------------------------------------------
    # Public Interface
    # ---------------------------------------------------------

    def generate_customer_summary(
        self,
        customer_profile: Dict[str, Any],
        assessment: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Generate a complete customer summary.

        Parameters
        ----------
        customer_profile : dict

        assessment : dict

        Returns
        -------
        dict
        """

        summary = {

            "overall_risk":
                assessment["overall_summary"]["rating"],

            "executive_summary":
                self._build_executive_summary(
                    customer_profile,
                    assessment
                ),

            "strengths":
                self._identify_strengths(
                    assessment
                ),

            "risk_factors":
                self._identify_risk_factors(
                    assessment
                ),

            "key_observations":
                self._identify_key_observations(
                    customer_profile
                ),

            "supporting_evidence":
                self._collect_supporting_evidence(
                    assessment
                )
        }

        return summary

    # ---------------------------------------------------------
    # Summary Builders
    # ---------------------------------------------------------

    def _build_executive_summary(
        self,
        customer_profile: Dict[str, Any],
        assessment: Dict[str, Any]
    ) -> str:
        """
        Build executive summary.

        Returns
        -------
        str
        """

        raise NotImplementedError

    def _identify_strengths(
        self,
        assessment: Dict[str, Any]
    ) -> List[str]:
        """
        Identify customer strengths.
        """

        raise NotImplementedError

    def _identify_risk_factors(
        self,
        assessment: Dict[str, Any]
    ) -> List[str]:
        """
        Identify customer risk factors.
        """

        raise NotImplementedError

    def _identify_key_observations(
        self,
        customer_profile: Dict[str, Any]
    ) -> List[str]:
        """
        Identify key customer observations.
        """

        raise NotImplementedError

    def _collect_supporting_evidence(
        self,
        assessment: Dict[str, Any]
    ) -> List[str]:
        """
        Collect assessment evidence.

        Returns
        -------
        List[str]
        """

        raise NotImplementedError
